name: Ping Spring Boot From Frontend
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Spring Boot From Frontend
        run: curl -X GET "https://resonating.vercel.app/api/ping"

