name: Ping Spring Boot From Frontend 

on:
  schedule:
    - cron: "* * * * *"  

jobs:
  ping:
    runs-on: ubuntu-22.04 
    steps:
      - name: Ping Spring Boot From Frontend
        run: |
          curl -fsS --retry 3 --max-time 10 "https://resonance-backend.onrender.com/health"

